#define t_any 		0
#define t_world		1
#define t_operator	2
#define t_int 		3
#define t_ident		4
#define t_bool 		5
#define t_reaction	6
#define t_redex 	7 
#define t_reactum	8
#define Node		0
#define Computation	1
#define Value		2
#define Reaction	3
#define Redex		4
#define Reactum		5
#define plus		1
#define sub			2
#define mult		3
#define div			4